name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.abhinaychary12 }}
          password: ${{ secrets.Abhinay@1212 }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.abhinaychary12 }}/skillmentor-app .
          docker push ${{ secrets.abhinaychary12 }}/skillmentor-app